      - name: Apply agent edit
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          FILE_PATH: ${{ github.event.inputs.file }}
          INSTRUCTIONS: ${{ github.event.inputs.instructions }}
        run: |
          python - <<'PY'
          import os, pathlib
          from openai import OpenAI

          # ✅ Explicitly pass the key
          client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

          p = pathlib.Path(os.environ["FILE_PATH"])
          if not p.exists():
              raise SystemExit(f"File not found: {p}")

          original = p.read_text(encoding="utf-8")
          instructions = os.environ["INSTRUCTIONS"]

          system = "You are a meticulous web editor. Output ONLY the full, final file content—no commentary."
          user = (
              "Edit the file below according to the instructions.\n\n"
              f"FILE_PATH: {p}\n"
              "BEGIN_FILE\n"
              f"{original}\n"
              "END_FILE\n\n"
              f"INSTRUCTIONS:\n{instructions}\n"
          )

          resp = client.chat.completions.create(
              model="gpt-5",
              messages=[{"role":"system","content":system},
                        {"role":"user","content":user}],
              temperature=0
          )
          new_content = resp.choices[0].message.content
          p.write_text(new_content, encoding="utf-8")
          PY
